# Generated by Django 3.0 on 2019-12-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comission',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.CharField(max_length=2000)),
                ('deadline', models.DateTimeField()),
                ('comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbsite.Comission')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_st', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('course', models.SmallIntegerField()),
                ('password', models.CharField(default='qwertyuiop', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task_executor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pbsite.Task')),
                ('who_do', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pbsite.User')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=200)),
                ('news_description', models.CharField(max_length=2000)),
                ('comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbsite.Comission')),
            ],
        ),
        migrations.CreateModel(
            name='Comission_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbsite.Comission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbsite.User')),
            ],
        ),
        migrations.AddField(
            model_name='comission',
            name='chairman',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pbsite.User'),
        ),
    ]
