# Generated by Django 3.0.1 on 2019-12-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191213_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vk_uid',
            field=models.IntegerField(default=0),
        ),
    ]
