# Generated by Django 3.0.1 on 2019-12-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_vk_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vk_uid',
        ),
        migrations.AddField(
            model_name='user',
            name='user_login',
            field=models.CharField(default='', max_length=30),
        ),
    ]
