# Generated by Django 3.0 on 2019-12-04 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comission',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comission_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Comission')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=200)),
                ('news_description', models.CharField(max_length=2000)),
                ('comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Comission')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.CharField(max_length=2000)),
                ('deadline', models.DateTimeField()),
                ('comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Comission')),
            ],
        ),
        migrations.CreateModel(
            name='Task_executor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Task')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_st', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('course', models.SmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='task_executor',
            name='who_do',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
        migrations.AddField(
            model_name='comission_member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
        migrations.AddField(
            model_name='comission',
            name='chairman',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
    ]
